name: CodeQL Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2
