jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Dev
        run: firebase deploy --only hosting:dev

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Staging
        run: firebase deploy --only hosting:staging

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Prod
        run: firebase deploy --only hosting:prod
